<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_FP</name>
   <tag></tag>
   <elementGuidId>c06ccb3d-ca3e-4e09-b151-5c24b0e84d8b</elementGuidId>
   <imagePath>../../Desktop/checkbox.png</imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.checkbox__label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
</WebElementEntity>
