<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text</name>
   <tag></tag>
   <elementGuidId>1f45215b-b257-4383-b40b-54d2f5e6f550</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tinymce>p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id=&quot;tinymce&quot;]/p</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Frame/text area frame</value>
   </webElementProperties>
</WebElementEntity>
